### ISSUE TITLE
gh actions: further investigate if we can extract the target branch when pushing a tag

### ISSUE THREAD

**Issue by mrozitron** [alphasoc/flightsim#35]
This would help ensure we don't kick off a release from something like `flightsim@foobranch@v1.0.0`.

Can dump context as below:
```
foo.yml:
...
  jobs:
  ...
      steps:
        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJSON(github) }}
          run: echo "$GITHUB_CONTEXT"
        - name: Dump job context
          env:
            JOB_CONTEXT: ${{ toJSON(job) }}
          run: echo "$JOB_CONTEXT"
        - name: Dump steps context
          env:
            STEPS_CONTEXT: ${{ toJSON(steps) }}
          run: echo "$STEPS_CONTEXT"
        - name: Dump runner context
          env:
            RUNNER_CONTEXT: ${{ toJSON(runner) }}
          run: echo "$RUNNER_CONTEXT"
        - name: Dump strategy context
          env:
            STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
          run: echo "$STRATEGY_CONTEXT"
        - name: Dump matrix context
          env:
            MATRIX_CONTEXT: ${{ toJSON(matrix) }}
          run: echo "$MATRIX_CONTEXT"
```
